import { jsPDF } from 'jspdf';
import 'jspdf-autotable';

export const generateMarkdownReport = (review, code, language) => {
  const timestamp = new Date().toISOString();
  
  let report = `# AI Code Review Report
Generated: ${timestamp}

---

## Overview
- **Score**: ${review.score}/10
- **Language**: ${language}
- **Review Type**: ${review.reviewType || 'Quality Review'}

---

## Summary
${review.summary}

---

## Complexity Analysis
- **Time Complexity**: ${review.timeComplexity || 'N/A'}
- **Space Complexity**: ${review.spaceComplexity || 'N/A'}

---

## Security Risk Level
${review.securityRiskLevel ? review.securityRiskLevel.toUpperCase() : 'N/A'}

${review.securityRiskLevel === 'critical' || review.securityRiskLevel === 'high' ? '⚠️ Immediate attention required!' : ''}

---

## Bugs Found
${review.bugs && review.bugs.length > 0 ? review.bugs.map((bug, i) => `
### Bug ${i + 1}
- **Line**: ${bug.line || 'N/A'}
- **Issue**: ${bug.issue}
- **Severity**: ${bug.severity?.toUpperCase() || 'LOW'}
- **Fix**: ${bug.fix}
`).join('\n') : 'No bugs found. ✅'}

---

## Security Issues
${review.securityIssues && review.securityIssues.length > 0 ? review.securityIssues.map((issue, i) => `
### Issue ${i + 1}
- **Line**: ${issue.line || 'N/A'}
- **Issue**: ${issue.issue}
- **Severity**: ${issue.severity?.toUpperCase() || 'LOW'}
- **Recommendation**: ${issue.recommendation}
`).join('\n') : 'No security issues found. ✅'}

---

## Performance Issues
${review.performanceIssues && review.performanceIssues.length > 0 ? review.performanceIssues.map((issue, i) => `
### Issue ${i + 1}
- **Line**: ${issue.line || 'N/A'}
- **Issue**: ${issue.issue}
- **Severity**: ${issue.severity?.toUpperCase() || 'LOW'}
- **Suggestion**: ${issue.suggestion}
`).join('\n') : 'No performance issues found. ✅'}

---

## Code Quality Issues
${review.codeQualityIssues && review.codeQualityIssues.length > 0 ? review.codeQualityIssues.map((issue, i) => `
### Issue ${i + 1}
- **Line**: ${issue.line || 'N/A'}
- **Issue**: ${issue.issue}
- **Severity**: ${issue.severity?.toUpperCase() || 'LOW'}
- **Suggestion**: ${issue.suggestion}
`).join('\n') : 'No code quality issues found. ✅'}

---

## Best Practices
${review.bestPractices && review.bestPractices.length > 0 ? review.bestPractices.map((practice, i) => `- ${practice}`).join('\n') : 'No specific recommendations.'}

---

## AI-Generated Test Cases
${review.testCases && review.testCases.length > 0 ? review.testCases.map((test, i) => `
### Test Case ${i + 1}
- **Input**: ${test.input}
- **Expected Output**: ${test.expectedOutput}
- **Description**: ${test.description}
`).join('\n') : 'No test cases generated.'}

---

## Original Code
\`\`\`${language.toLowerCase()}
${code}
\`\`\`

---

## Improved Code
\`\`\`${language.toLowerCase()}
${review.improvedCode || 'N/A'}
\`\`\`

---

## Explanation of Changes
${review.explanation}

---

*Report generated by AI Code Reviewer*
`;

  return report;
};

export const downloadMarkdownReport = (review, code, language) => {
  const report = generateMarkdownReport(review, code, language);
  const blob = new Blob([report], { type: 'text/markdown' });
  const url = URL.createObjectURL(blob);
  const link = document.createElement('a');
  link.href = url;
  link.download = `code-review-${Date.now()}.md`;
  document.body.appendChild(link);
  link.click();
  document.body.removeChild(link);
  URL.revokeObjectURL(url);
};

export const downloadPdfReport = (review, code, language) => {
  const doc = new jsPDF();
  const pageWidth = doc.internal.pageSize.getWidth();
  let yPos = 20;

  // Title
  doc.setFontSize(20);
  doc.setTextColor(14, 165, 233); // primary-500
  doc.text('AI Code Review Report', pageWidth / 2, yPos, { align: 'center' });
  yPos += 15;

  // Score
  doc.setFontSize(16);
  doc.setTextColor(0, 0, 0);
  doc.text(`Score: ${review.score}/10`, pageWidth / 2, yPos, { align: 'center' });
  yPos += 10;

  // Metadata
  doc.setFontSize(10);
  doc.setTextColor(100, 100, 100);
  doc.text(`Language: ${language} | Generated: ${new Date().toLocaleString()}`, pageWidth / 2, yPos, { align: 'center' });
  yPos += 15;

  // Summary
  doc.setFontSize(12);
  doc.setTextColor(0, 0, 0);
  doc.text('Summary', 20, yPos);
  yPos += 7;
  doc.setFontSize(10);
  const summaryLines = doc.splitTextToSize(review.summary || 'No summary available', pageWidth - 40);
  doc.text(summaryLines, 20, yPos);
  yPos += summaryLines.length * 5 + 10;

  // Complexity
  if (review.timeComplexity || review.spaceComplexity) {
    doc.setFontSize(12);
    doc.text('Complexity Analysis', 20, yPos);
    yPos += 7;
    doc.setFontSize(10);
    if (review.timeComplexity) doc.text(`Time: ${review.timeComplexity}`, 25, yPos);
    if (review.spaceComplexity) doc.text(`Space: ${review.spaceComplexity}`, 100, yPos);
    yPos += 15;
  }

  // Bugs
  if (review.bugs && review.bugs.length > 0) {
    doc.setFontSize(12);
    doc.text('Bugs Found', 20, yPos);
    yPos += 7;
    
    const bugData = review.bugs.map(bug => [
      bug.line || 'N/A',
      bug.issue.substring(0, 50) + (bug.issue.length > 50 ? '...' : ''),
      bug.severity?.toUpperCase() || 'LOW',
      bug.fix ? bug.fix.substring(0, 40) + (bug.fix.length > 40 ? '...' : '') : 'N/A'
    ]);

    doc.autoTable({
      startY: yPos,
      head: [['Line', 'Issue', 'Severity', 'Fix']],
      body: bugData,
      theme: 'striped',
      headStyles: { fillColor: [239, 68, 68] },
      styles: { fontSize: 8 }
    });
    yPos = doc.lastAutoTable.finalY + 15;
  }

  // Security Issues
  if (review.securityIssues && review.securityIssues.length > 0) {
    if (yPos > 250) {
      doc.addPage();
      yPos = 20;
    }
    doc.setFontSize(12);
    doc.text('Security Issues', 20, yPos);
    yPos += 7;
    
    const secData = review.securityIssues.map(issue => [
      issue.line || 'N/A',
      issue.issue.substring(0, 50) + (issue.issue.length > 50 ? '...' : ''),
      issue.severity?.toUpperCase() || 'LOW'
    ]);

    doc.autoTable({
      startY: yPos,
      head: [['Line', 'Issue', 'Severity']],
      body: secData,
      theme: 'striped',
      headStyles: { fillColor: [220, 38, 38] },
      styles: { fontSize: 8 }
    });
    yPos = doc.lastAutoTable.finalY + 15;
  }

  // Best Practices
  if (review.bestPractices && review.bestPractices.length > 0) {
    if (yPos > 250) {
      doc.addPage();
      yPos = 20;
    }
    doc.setFontSize(12);
    doc.text('Best Practices', 20, yPos);
    yPos += 7;
    doc.setFontSize(9);
    review.bestPractices.forEach((practice, i) => {
      const lines = doc.splitTextToSize(`${i + 1}. ${practice}`, pageWidth - 40);
      if (yPos + lines.length * 5 > 280) {
        doc.addPage();
        yPos = 20;
      }
      doc.text(lines, 25, yPos);
      yPos += lines.length * 5;
    });
    yPos += 10;
  }

  // Test Cases
  if (review.testCases && review.testCases.length > 0) {
    if (yPos > 220) {
      doc.addPage();
      yPos = 20;
    }
    doc.setFontSize(12);
    doc.text('Test Cases', 20, yPos);
    yPos += 7;

    const testData = review.testCases.map(test => [
      test.input.substring(0, 30) + (test.input.length > 30 ? '...' : ''),
      test.expectedOutput.substring(0, 30) + (test.expectedOutput.length > 30 ? '...' : ''),
      test.description.substring(0, 40) + (test.description.length > 40 ? '...' : '')
    ]);

    doc.autoTable({
      startY: yPos,
      head: [['Input', 'Expected Output', 'Description']],
      body: testData,
      theme: 'striped',
      headStyles: { fillColor: [34, 197, 94] },
      styles: { fontSize: 8 }
    });
  }

  // Footer
  const pageCount = doc.internal.getNumberOfPages();
  for (let i = 1; i <= pageCount; i++) {
    doc.setPage(i);
    doc.setFontSize(8);
    doc.setTextColor(150, 150, 150);
    doc.text(
      `Page ${i} of ${pageCount} | Generated by AI Code Reviewer`,
      pageWidth / 2,
      doc.internal.pageSize.getHeight() - 10,
      { align: 'center' }
    );
  }

  doc.save(`code-review-${Date.now()}.pdf`);
};

export const copyToClipboard = async (text) => {
  try {
    await navigator.clipboard.writeText(text);
    return true;
  } catch (err) {
    console.error('Failed to copy:', err);
    return false;
  }
};
